image: php:8.0

before_script:
    # Install git, the php image doesn't have installed
    - apt-get update -yqq
    - apt-get install git -yqq
    # Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cat ~/.ssh/config


    # Install mysql driver
    #- docker-php-ext-install pdo_mysql

    # Install composer
    #- curl -sS https://getcomposer.org/installer | php

    # Install all project dependencies
    #- php composer.phar install


stages:
    #- build
    - test
    - deploy

#build_job:
    #stage: build


test_job:
    stage: test
    script:
        - php test AllTest

deploy_staging:
    stage: deploy
    script:
        - echo $SSH_HOST
        - ssh -tt $SSH_HOST
        - ls -la
        - exit
    environment:
        name: staging
    only:
        - develop