#!/usr/bin/env php
<?php 

require('./classes/Root/Core.php');

Root\Core::initialize();

$request = Root\Request\TestingRequest::current();

echo $request->response() . PHP_EOL;

$exitCode = ($request->test()->success()) ? 0 : 1;
exit($exitCode);